### ISSUE TITLE
'load_cti_kg()' function is not defined

### ISSUE THREAD

**Issue by ESTA-2509** [NanArtist/APT-MMF#2]
I am facing an issue with 'load_cti_kg()' function is not defined.
Could you please help me to check the position of 'load_cti_kg()' function defined?

---------------------------------------------------------------------
(APT-MMF) C:\Users\MyComputer\APT-MMF> python Main.py
Traceback (most recent call last):
  File "C:\Users\MyComputer\APT-MMF\Main.py", line 98, in <module>
    model_run(args)
  File "C:\Users\MyComputer\APT-MMF\Main.py", line 14, in model_run
    labels,num_classes,train_mask,val_mask,test_mask,attribute_type_feat,nlt_feat,topo_relation_feat,node_type_vec,heterG_adj,report_node,homoG_adj_MPs = load_cti_kg()
NameError: name 'load_cti_kg' is not defined

---------------------------------------------------------------------

Thank you

**Comment by morzen** [comment]
Hello,

You are not alone I am also facing a similar situation despite following the installation step defined in the README file.
![image](https://github.com/user-attachments/assets/f554dd89-c40d-48bc-894d-3b0b49a93b7b)

I thank in advance anyone with suggestions or ideas on overcoming this issue.

kind regards,
Barnabe Malandain



PS, in your code you have a comment above the line failing saying "# load data. For more information, see Attribution/emb/emb.md."

So I did.
<img width="1642" alt="Screenshot 2024-07-26 at 13 09 48" src="https://github.com/user-attachments/assets/55393cbb-6286-424d-a776-349a0b43c96e">

As many scientists are going to try and reproduce your experiment, I concur with [ESTA-2509]'s other issue of providing the dataset, it would be more optimized when trying to reproduce the experiment as well as try to either compare or improve it against other state-of-the-art programs.
Could you please provide the dataset to the community and make it publicly available?
